name: Benchmark Tests

on: workflow_dispatch

jobs:
  build:
    env:
      # We use these variables to convert between tox and GHA version literals
      py37: 3.7
      py38: 3.8
      py39: 3.9
      py310: "3.10"
      py311: "3.11"
      pypy3: pypy-3.7
      RUN_MATRIX_COMBINATION: ${{ matrix.python-version }}-${{ matrix.package }}-${{
        matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        python-version: [py37]
        package: ["api", "sdk", "semantic", "getting", "shim", "exporter", "protobuf",
          "propagator"]
        os: [ubuntu-20.04]
    steps:
    - name: Checkout Core Repo @ SHA - ${{ github.sha }}
      uses: actions/checkout@v2
    - name: Set up Python ${{ env[matrix.python-version] }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env[matrix.python-version] }}
        architecture: 'x64'
    - name: Install tox
      run: pip install tox==3.27.1 -U tox-factor
    - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
      uses: actions/cache@v2
      with:
        path: |
          .tox
          ~/.cache/pip
        key: v3-tox-cache-${{ env.RUN_MATRIX_COMBINATION }}-${{ hashFiles('tox.ini',
          'dev-requirements.txt') }}-core
    - name: run tox
      run: tox -f ${{ matrix.python-version }}-${{ matrix.package }} -- --benchmark-json=${{
        env.RUN_MATRIX_COMBINATION }}-benchmark.json
#       - name: Find and merge benchmarks
#         id: find_and_merge_benchmarks
#         run: >-
#           jq -s '.[0].benchmarks = ([.[].benchmarks] | add)
#           | if .[0].benchmarks == null then null else .[0] end'
#           $(find . -name '*${{ matrix.package }}*-benchmark.json') > output.json
#           && echo "json_plaintext=$(cat output.json)" >> $GITHUB_OUTPUT
#       - name: Report on benchmark results
#         if: steps.find_and_merge_benchmarks.outputs.json_plaintext != 'null'
#         uses: rhysd/github-action-benchmark@v1
#         with:
#           name: OpenTelemetry Python Benchmarks - Python ${{ env[matrix.python-version ]}} - ${{ matrix.package }}
#           tool: pytest
#           output-file-path: output.json
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           max-items-in-chart: 100
#           # Alert with a commit comment on possible performance regression
#           alert-threshold: 200%
#           fail-on-alert: true
#           # Make a commit on `gh-pages` with benchmarks from previous step
#           auto-push: ${{ github.ref == 'refs/heads/main' }}
#           gh-pages-branch: gh-pages
#           benchmark-data-dir-path: benchmarks